steps:
  - label: ":maven: Build and Deploy"
    checkout:
      ssh_secret: "GITHUB_SSH_KEY"
    command:
      - java -version
      - mvn clean deploy -Prelease
    agents:
      queue: "java_build_queue_aws"
